PaymentGateway/Controllers/PaymentProcessorController.cs
using Gyuan.Infrastructure.Broker;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using PaymentGateway.Data;
using PaymentGateway.Models;
using PaymentGateway.Services;
using System;
using System.Net.Http;
using System.Threading.Tasks;

namespace PaymentGateway.Controllers
{
    public class PaymentProcessorController : Controller
    {
        readonly ILogger _logger;
        readonly ApplicationDbContext _db;
        readonly IMemoryCache _cache;
        //readonly IExchangeBroker _broker;
        readonly IPaymentService _paymentService;

        public PaymentProcessorController(
            ILoggerFactory loggerFactory,
            ApplicationDbContext db,
            //IExchangeBroker broker,
            IMemoryCache cache,
            IPaymentService paymentService)
        {
            _logger = loggerFactory.CreateLogger(nameof(PaymentProcessorController));
            _db = db;
            _cache = cache;
            //_broker = broker;
            _paymentService = paymentService;
        }

        public async Task<IActionResult> PayCurrencySelect(string id)
        {
            var payment = await GetPayment(id);
            if (payment == null)
                return View("Error");

            return View(payment);
        }

        public async Task<IActionResult> Invoice(string id, string currency)
        {
            var payment = await GetPayment(id);
            if (payment == null)
                return View("Error");

            await _paymentService.OnlineSale(payment, currency);

            return View(payment);
        }

        public async Task<IActionResult> Cancel(string id)
        {
            var payment = await GetPayment(id);
            if (payment == null)
                return View("Error");

            return Redirect(payment.CancelUrl);
        }

        public async Task<IActionResult> Success(string id)
        {
            var payment = await GetPayment(id);
            if (payment == null)
                return View("Error");

            return Redirect(payment.CompleteUrl);
        }

        public async Task<IActionResult> PaymentReceived(string id)
        {
            var payment = await GetPayment(id);
            if (payment == null)
                    return View("Error");
            return View(payment);
        }

        async Task<Payment> GetPayment(string id)
        {
            _cache.TryGetValue(id, out Payment payment);
            if (payment == null)
                payment = await _db.Payment
                    .Include(p => p.Terminal)
                    .FirstOrDefaultAsync(t => t.Id == id);
            return payment;
        }

        public async Task<IActionResult> GetStatus(string id)
        {
            //var prms = new BrokerExchangeStatusParams()
            //{
            //    ExchangeId = id
            //};

            try
            {
                //var brokerResult = await _broker.ExchangeStatus(prms);

                var res = await _paymentService.GetSaleStatus(id);

                var payment = await GetPayment(id);
                if (payment?.CallbackUrl != null)
                {
                    using (var httpClient = new HttpClient())
                    {
                        await httpClient.GetAsync(new Uri(payment.CallbackUrl + $"&id={payment.Id}&order_id={payment.ExternalOrderId}"));
                    }
                }

                return Json((int)res.Status);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex.Message);
                return Json(ex.Message);
            }
        }
       
    }
}

PaymentGateway/Views/PaymentProcessor/Invoice.cshtml
@model PaymentGateway.Models.Payment
@{
    Layout = null;
}
@{
    var storeName = Model.Terminal?.Name ?? "Store";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="google" value="notranslate">
    <title>Payment</title>
    <meta name="viewport" content="width=device-width, initial-scale=0.5">
    <link rel='stylesheet' href='~/css/style.css' type='text/css' media='all' />
</head>
<body>
    <input type="hidden" id="paymentId" value="@Html.Raw(Model.Id)" />

    <div class='maincontainer'>
        <div class='maindisplay'>
            <div class='header'>
                <div class='toplogo'>
                    <img src='~/images/logo.png'>
                </div>
                <div class='order-detail'>
                    @storeName<br>
                    Your Order ID #@Model.ExternalOrderId
                </div>
                <div class='clear'></div>
            </div>

            <div class='caption'>
                Your payment to @storeName
            </div>

            To complete your payment, please send @Model.PayAmount.ToString("N8") @Model.PayCurrency to the address bellow
            <br><br>
            <strong>@Model.PayWalletAddress</strong>
            <br><br>
            <div id="qrCode" align='center'></div>

            <div class='order-details'>
                <table>
                    <tr>
                        <td class='caption'>Amount:</td>
                        <td class='caption'>@Model.SaleAmount.ToString("N2") @Model.SaleCurrency</td>
                    </tr>
                </table>
            </div>

            <div class='buttonsection'>
                <a href='@Url.Action("Cancel", "PaymentProcessor", new { id = Model.Id })'><button class='cancel'>Return to @storeName</button></a>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript" src="~/lib/qrcode.js"></script>
    <script type="text/javascript">
        var intervalID = -1;

        new QRCode(document.getElementById("qrCode"),
            {
                text: "@Html.Raw(Model.PayWalletAddress)",
                width: 181,
                height: 181
            });

        function GetStatus() {
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetStatus", "PaymentProcessor", new { id = Model.Id })',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (recData)
                {
                    if (recData >= 3 && intervalID != -1) {
                        clearInterval(intervalID);

                        window.location.href = '@Url.Action("PaymentReceived", "PaymentProcessor", new { id = Model.Id })';
                    }
                },
            });
        }

        function OnClick() {
            const el = document.createElement('textarea');
            el.value = '@Html.Raw(Model.PayWalletAddress)';
            el.setAttribute('readonly', '');
            el.style.position = 'absolute';
            el.style.left = '-9999px';
            document.body.appendChild(el);
            el.select();
            document.execCommand('copy');
            document.body.removeChild(el);
        }

        intervalID = setInterval(GetStatus, 5000);
        document.getElementById("qrCode").addEventListener("click", function () { OnClick(); }, false);
    </script>

</body>
</html>

PaymentGateway/Views/PaymentProcessor/PayCurrencySelect.cshtml
@model PaymentGateway.Models.Payment
@{
    Layout = null;
}
@{
    var storeName = Model.Terminal?.Name ?? "Store";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="google" value="notranslate">
    <title>Pay Currency Select</title>
    <meta name="viewport" content="width=device-width, initial-scale=0.5">
    <link rel='stylesheet' href='~/css/style.css' type='text/css' media='all' />
</head>
<body>
    <input type="hidden" id="paymentId" value="@Html.Raw(Model.Id)" />

    <div class='maincontainer'>

        <div class='maindisplay'>
            <div class='header'>
                <div class='toplogo'>
                    <img src='~/images/logo.png'>
                </div>
                <div class='order-detail'>
                    @storeName<br>
                    Your Order ID #@Model.ExternalOrderId
                </div>
                <div class='clear'></div>
            </div>

            <div class='caption'>
                Choose Cryptocurrency for your payment
            </div>

            <div class='mainsection'>
                <table>
                    <tr>
                        <td colspan=2 class='items'>
                            <div class='item'>
                                <input type='radio' name="Cryptocurrency" id='item1' value="BTC" checked>
                                <label for='item1'>
                                    <img src='~/images/bitcoin.png'><br>
                                    BTC
                                </label>
                            </div>

                            <div class='item'>
                                <input type='radio' name="Cryptocurrency" id='item2' value="ETH">
                                <label for='item2'>
                                    <img src='~/images/eth.png'><br>
                                    ETH
                                </label>
                            </div>
                            <div class='item'>
                                <input type='radio' name="Cryptocurrency" id='item3' value="GRFT">
                                <label for='item3'>
                                    <img src='~/images/gyuan.png'><br>
                                    GRFT
                                </label>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>


            <div class='order-details'>
                <table>
                    @*<tr>
                            <td class='order-caption' colspan=2>Your Order Details</td>
                        </tr>
                        <tr>
                            <td>Polo X 1</td>
                            <td>$20</td>
                        </tr>
                        <tr>
                            <td colspan=2 class='order-divider'></td>
                        </tr>
                        <tr>
                            <td>Subtotal</td>
                            <td>$20</td>
                        </tr>
                        <tr>
                            <td>Shipping</td>
                            <td>$12</td>
                        </tr>
                        <tr>
                            <td colspan=2 class='order-divider'></td>
                        </tr>*@

                    <tr>
                        <td class='caption'>Amount:</td>
                        <td class='caption'>@Model.SaleAmount.ToString("N2") @Model.SaleCurrency</td>
                    </tr>
                </table>
            </div>

            <div class='buttonsection twocols'>
                <a href='@Url.Action("Cancel", "PaymentProcessor", new { id = Model.Id })'><button class='cancel'>Return to @storeName</button></a>
                <button id="b1">Pay</button>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script>
        function Navigate() {
            var crypto = $('[name=Cryptocurrency]:checked').val();
            var action = '@Url.Action("Invoice", "PaymentProcessor")';
            window.location.href = action + "?currency=" + encodeURI(crypto) + "&id=" + encodeURI("@Model.Id");
        }
        document.getElementById("b1").addEventListener("click", function () { Navigate(); }, false);
    </script>

</body>
</html>

PaymentGateway/Views/PaymentProcessor/PaymentReceived.cshtml
@model PaymentGateway.Models.Payment
@{
    Layout = null;
}
@{
    var storeName = Model.Terminal?.Name ?? "Store";
}

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="google" value="notranslate">
    <title>Payment Received</title>
    <meta name="viewport" content="width=device-width, initial-scale=0.5">
    <meta http-equiv="refresh" content="5;URL=@Url.Action("Success", "PaymentProcessor", new { id = Model.Id })" />
    <link rel='stylesheet' href='~/css/style.css' type='text/css' media='all' />
</head>
<body>

    <div class='maincontainer'>
        <div class='maindisplay'>

            <div class='header'>
                <div class='toplogo'>
                    <img src='~/images/logo.png'>
                </div>
                <div class='order-detail'>
                    @storeName<br>
                    Your Order ID #@Model.ExternalOrderId
                </div>
                <div class='clear'></div>
            </div>
            <div class='top-line green'>
            </div>
            <br>
            <img src='~/images/check.png' class='status-icon'>
            <div class='caption'>
                You payment is completed!
            </div>
            We successfully received @Model.PayAmount.ToString("N8") @Model.PayCurrency from you.
            <br>

            <div class='buttonsection'>
                <a href='@Url.Action("Success", "PaymentProcessor", new { id = Model.Id })'><button class='cancel'>Return to @storeName</button></a>
            </div>

        </div>
    </div>

</body>
</html>